version: "3.4"

services:
  web:
    build: ./
    container_name: php_web
    ports: 
      - "80:80"
    depends_on: 
      - db
    environment: 
      - DATABASE_HOST=db
    volumes: 
      - ./html:/var/www/localhost/htdocs
    stdin_open: true
    tty: true
    networks:
      - web-db-net
  db:
    build: ./db
    restart: on-failure
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    volumes:
      - "./db/data:/var/lib/mysql"
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - web-db-net
networks:
  web-db-net: